version: "3"

services:
  
  image_server:
    build: .
    command: npm start
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
        - tcc-net

networks:
  tcc-net:
    driver: bridge